publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785]
    pos2: [0, 0]
    pos3: [-0.785, -0.785]
    pos4: [0, 0]

# 这是一个YAML文件的示例，用于配置ROS节点的参数。具体来说，这个文件配置了一个名为"publisher_forward_position_controller"的节点的参数。

# 节点的参数如下：

# wait_sec_between_publish: 这是一个等待时间，表示在每次发布消息之间等待的秒数。在这个例子中，设置为5秒。

# publish_topic: 这是指定要发布消息的主题名称。在这个例子中，消息将发布到"/forward_position_controller/commands"主题。

# goal_names: 这是一个字符串数组，表示不同的目标名称。在这个例子中，有四个目标名称，分别为"pos1"、"pos2"、"pos3"和"pos4"。

# pos1、pos2、pos3、pos4: 这些是与目标名称对应的位置坐标。每个目标名称都对应一个包含两个值的数组，表示X和Y轴的位置坐标。在这个例子中，"pos1"对应的位置坐标为[0.785, 0.785]，"pos2"对应的位置坐标为[0, 0]，"pos3"对应的位置坐标为[-0.785, -0.785]，"pos4"对应的位置坐标为[0, 0]。

# 这个YAML文件中的参数用于配置一个ROS节点，该节点将在指定的主题上发布带有不同位置坐标的目标消息。节点将在每次发布消息之间等待一定的时间。这样的配置可以用于控制机器人或其他系统的位置控制器，使其按照预定的位置目标进行运动。